fork = false
frame = "none"
idle = true
maximized = false
no-multigrid = true
srgb = false
tabs = false
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font] 
normal = "Maple Mono NF"
size = 10.5

[window]
padding_top = 0
padding_bottom = 0
padding_left = 0
padding_right = 0
